language: python
install:
  - cd YouTube_Closed_Captioning_API
  - python3 -m pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: foreignwhispers
  env: Foreignwhispers-env
  on:
    repo: devmcdonald/AI-ML/YouTube_Closed_Captioning_API
    branch:
      - develop
  cleanup: 'false'
